version: '3.8'
services:

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: cqrsdb                   # Nome do banco de dados
      POSTGRES_USER: cqrsuser               # Usuário do banco de dados
      POSTGRES_PASSWORD: cqrssecret         # Senha do banco de dados
    ports:
      - "5432:5432"                         # Mapeamento de porta
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/       # Monta o diretório local 'data' como volume

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-net
volumes:
  axonserver-data:
  axonserver-events:
  axonserver-config:
networks:
  axon-net: